title: Chris Buckley
description: 'Add "font-display: swap" to Google Fonts'

url: https://cmbuckley.co.uk
baseurl: /gfont-swap

repository: cmbuckley/gfont-swap
remote_theme: "cmbuckley/cmbuckley.github.io"
suppress_fingerprints: true

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
